### ISSUE TITLE
View synonyms (link)

### ISSUE THREAD

**Issue by grahamperrin** [smoqadam/english-learners-dictionary#3]
The **View synonyms** link does not work. 

In the screenshot below, it appears to be concatenated with the preceding multi-word phrase: 

![image](https://user-images.githubusercontent.com/192271/62410928-c7c10f00-b5e4-11e9-93ac-e987ecf60829.png)

**Comment by smoqadam** [comment]
Thanks for the report. I will fix it in the next version.

**Comment by smoqadam** [comment]
Fixed in version 1.4
