### ISSUE TITLE
Apparently endless wait

### ISSUE THREAD

**Issue by grahamperrin** [smoqadam/english-learners-dictionary#5]
Hi

At https://pastebin.com/ for example: 

![image](https://user-images.githubusercontent.com/192271/70799887-c8439080-1da2-11ea-8afc-1ca04f9a7442.png)

I tried outdated version 1.3, the same problem. 

Also, a minor spelling error: *wait …* (not *waite…*)

**Comment by smoqadam** [comment]
Hi Graham, Thanks for the report. It seems you wanted to lookup for the word inside the textarea by choosing the Translate from the context menu. If this was the case, yes this is the issue that need to fix. Actually, it doesn't capture the selected words inside the input or textarea. I will fix it in next few days.

**Comment by smoqadam** [comment]
Fixed in this commit adde70e3

**Comment by grahamperrin** [comment]
Fix confirmed, thanks.
